int chickenMenu = int.Parse(Console.ReadLine());
int fishMenu = int.Parse(Console.ReadLine());
int veganMenu = int.Parse(Console.ReadLine());
double chickenMoney = chickenMenu * 10.35;
double fishMoney = fishMenu * 12.40;
double veganMoney = veganMenu * 8.15;
double totalMoney = chickenMoney + fishMoney + veganMoney;
double dessert = totalMoney * 0.2;
double total = dessert + totalMoney + 2.50;
Console.WriteLine(total);